- name: Install Kubernetes
  hosts: cp,wk
  become: true
  tasks:
  - name: Create sysctl.d/k8s.conf
    copy:
      dest: "/etc/sysctl.d/k8s.conf"
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
  - name: Run command sysctl --system
    command: sysctl --system



