- name: Install calicoctl
  hosts: cp
  gather_facts: False
  tasks:

  - name: Download calicoct
    get_url:
      url: https://github.com/projectcalico/calicoctl/releases/download/v3.15.0/calicoctl
      dest: /usr/local/bin/calicoctl
      mode: '0755'
    when: inventory_hostname == "kmaster0"
