---
- hosts: cp,wk
  tasks:
  - name: selinux setenforce 0
    command: setenforce 0
  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive
